language: objective-c
xcode_project: LayoutModules.xcodeproj
xcode_scheme: LayoutModules
osx_image: xcode7.1
before_install: true
install: true
git:
  submodules: false
script:
  - xctool -sdk iphonesimulator -project LayoutModules.xcodeproj -scheme LayoutModules build test
