language: objective-c
xcode_project: LayoutModules.xcodeproj
xcode_scheme: LayoutModules
osx_image: xcode8.2
before_install: true
install: true
git:
  submodules: false
script:
  - xcodebuild -sdk iphonesimulator -project LayoutModules.xcodeproj -scheme LayoutModules build
